import { ActionLink, Container, Section, Eyebrow, Heading, Text, Grid, ProjectCard, ArticleCard, EmptyState, SectionHeading } from '../components/ui';
import { Breadcrumb } from '../components/navigation';
import styles from './Pages.module.css';
export function Home(){return <><div className={styles.hero}><Container><Eyebrow>Independent technology lab / 001</Eyebrow><Heading as="h1">Explorando ideias.<br/><span className={styles.accent}>Construindo soluções.</span></Heading><p className={styles.lead}>Um laboratório independente de software, infraestrutura, eletrônica e experimentação aplicada a problemas reais.</p><div className={styles.actions}><ActionLink to="/projetos">Explorar projetos ↗</ActionLink><ActionLink to="/sobre" variant="outline">Conhecer o laboratório</ActionLink></div></Container></div><Section><Container><SectionHeading eyebrow="01 / Projetos" title="O que estamos construindo"/><div className={styles.spacer}><Grid><ProjectCard title="SysSnap" description="Coleta e relatórios técnicos de computadores." category="Software / Diagnóstico"/><ProjectCard title="WappHub" description="Experimentos com plataformas de comunicação e serviços." category="SaaS / Comunicação"/><ProjectCard title="PKSIG" description="Sistema de gestão para assistência técnica." category="Gestão / ERP"/></Grid></div><div className={styles.actions}><ActionLink to="/projetos" variant="outline">Ver projetos ↗</ActionLink></div></Container></Section><Section><Container><SectionHeading eyebrow="02 / Laboratório" title="Construir também é experimentar"/><Text>Provas de conceito, infraestrutura e ferramentas em evolução.</Text><ActionLink to="/lab" variant="outline">Acessar laboratório ↗</ActionLink></Container></Section><Section><Container><SectionHeading eyebrow="03 / Conhecimento" title="Notas do laboratório"/><Grid><ArticleCard title="Publicações em preparação" description="Artigos técnicos e registros de desenvolvimento serão publicados no M1."/></Grid><div className={styles.actions}><ActionLink to="/artigos" variant="outline">Explorar artigos ↗</ActionLink></div></Container></Section></>}
function Page({label,title,description,children}:{label:string;title:string;description:string;children?:React.ReactNode}){return <main className={styles.page}><Container><Breadcrumb items={[{label:title}]}/><Eyebrow>{label}</Eyebrow><Heading as="h1">{title}</Heading><p className={styles.pageintro}>{description}</p><div className={styles.details}>{children}</div></Container></main>}
export function Projects(){return <Page label="Projetos / 001" title="Projetos" description="Software, ferramentas e sistemas desenvolvidos no laboratório. O catálogo detalhado chega no M1."><Grid><ProjectCard title="SysSnap" category="Diagnóstico" description="Ferramenta técnica para relatórios de hardware."/><ProjectCard title="WappHub" category="Comunicação" description="Plataforma de software e comunicação."/><ProjectCard title="PKSIG" category="Gestão" description="ERP para assistência técnica."/></Grid></Page>}
export function ProjectDetails(){return <Page label="Projeto" title="Projeto em preparação" description="A página detalhada deste projeto será publicada no M1."><EmptyState title="Conteúdo indisponível" description="Ainda não há uma ficha pública validada para este projeto."/></Page>}
export function Lab(){return <Page label="Experiments / 002" title="Laboratório" description="Experimentos, pesquisas e provas de conceito em construção."><EmptyState title="Experimentos em preparação" description="O catálogo de experimentos será publicado em uma próxima etapa."/></Page>}
export function Articles(){return <Page label="Knowledge / 003" title="Artigos" description="Conhecimento técnico, documentação e notas de engenharia."><EmptyState title="Publicações em preparação" description="Os primeiros artigos chegam no M1."/></Page>}
export function About(){return <Page label="About / 004" title="Sobre o ULLN" description="ULLN é um laboratório digital independente dedicado à investigação e criação de soluções tecnológicas."><Heading as="h2">Tecnologia explorada. Soluções construídas.</Heading><Text>Software, infraestrutura, eletrônica e experimentação compartilham o mesmo espaço. Conheça os projetos e acompanhe sua evolução.</Text><a href="https://github.com/uillaneduardo" target="_blank" rel="noopener noreferrer">Repositórios no GitHub ↗</a></Page>}
export function NotFound(){return <Page label="404 / Not found" title="Página não encontrada" description="O endereço solicitado não existe ou foi movido."><ActionLink to="/">Voltar ao início ↗</ActionLink></Page>}
